### PR TITLE
Optimize the list of installed packages and add automated tests

### PR DESCRIPTION
**Pull request by vincent-zurczak**
Hello,

Here is a PR with several changes, including improving the list of installed packages, adding automated tests and completing the README file.

Once merged, you only have to enable the repository in Travis CI to have continuous integration.

### CODE REVIEW

**Comment by rstropek** [comment]
Hi @vincent-zurczak! Thank you very much for your pull request. I do not use Travis CI. Would it be possible to limit your changes to functional extensions without adding Travis? Greetings, Rainer.

**Comment by vincent-zurczak** [comment]
Hi Rainer,

Well, Travis CI is free and it would allow to detect any regression directly.
Continuous integration only takes few seconds to be setup.

If you insist, I can remove it.

**Comment by vincent-zurczak** [comment]
Hi Rainer. Any feedback on my last comment?  
Do you want me remove the configuration file for Travis CI? Or do you want some help to set up such an integration?

**Comment by rstropek** [comment]
I am fine with your Travis CI files if they are important for you. Merged your changes and tested everything for my use cases -> everything works fine. Build on Docker Hub also completed successfully. Thank you for your contribution.

**Pull request merged**
